### PR TITLE
Fix localization loading + Cleanup

### PR DESCRIPTION
**Pull request by Road-block**
make use of addon scope to implement localization without polluting the global environment
use the proper event for addon initalisation, make the event handler more generic make the yell filter bail out early if the filter option is not set / is false

I tried to comment new concepts liberally, but happy to expand further here.

### CODE REVIEW

**Comment by GovtGeek** [comment]
I appreciate the suggestions, but the branches are real works in progress. I commit to them often to make sure I don't lose work. If the branch ever goes into a pre-release state, I would love the suggestions submitted as issues for me to work through. Localization, while I assume is low in priority, was my next task since I've seen it implemented several ways.

I will be taking all of your changes in this pull request into consideration as I continue.

**Comment by Road-block** [comment]
But you have packaged this branch and put it up on curse.
My PR fixes issues with this file's: <https://www.curseforge.com/wow/addons/shut-up-rhonin/files/4550275> code.

**Comment by GovtGeek** [comment]
Oh well damn. I created a pre-release to test something and Curse snagged it as a full release. I'll have to fix that. Thanks!

**Comment by Road-block** [comment]
That package - aside changes I've made to make better use of the available framework - has a few actual problems.
1. `VARIABLES_LOADED` event hasn't been related to addon loading since a few expansions. It now fires when Blizzard CVars and Blizzard related addons load.
`ADDON_LOADED` with your addon name as first argument is the event that denotes X addon variables loaded.
2. The way the localization is implemented will 
  a leak the variable names to the global environment and 
  b only the last file's linked in .toc contents remain in memory (in this particular case  `ShutUpRhoninStrings_ru.lua`
Previous entries are overwritten.
3. Leaking other globals is not an outright logical bug but it make an addon prone to breaking other addons (or getting broken by them, if they clobber each other's variables put in global namespace.


**Edit:** The addon is mostly well made (especially for a first addon) 😃 
The addition of a slash command and options for the chat filter is a good next step, it's nice to see the concept evolving.
It's useful and simple enough that you probably don't want to use an addon framework (like Ace) for fancy options or localization.

**Comment by GovtGeek** [comment]
Yeah. It's been over a decade since I wrote addons. I had a half dozen with the most popular being a random mount addon before the mount journal. Hence me starting with a very small thing to do. I was mainly trying to figure out the options panel again. You included localization in your previous pull request so I was trying to figure that out too. I don't like localizations in the main file for several reasons and was working to break them out. With your request I noticed I forgot the check for locale altogether.

**Comment by GovtGeek** [comment]
I have an alpha build up that incorporates your changes with my style. Wouldn't mind a second set of eyes on it.

**Comment by Road-block** [comment]
> I have an alpha build up that incorporates your changes with my style. Wouldn't mind a second set of eyes on it.

If it is the code that's up in the yell-filter branch it's still not entirely correct, tbh I don't see what style has to do with it I'm sorry :)

The event handler is still wrong and imho harder to understand than the one in my pull request.
The function signature is [frame], event, ...
[frame] is implicit and is passed by the : colon notation.
event in this addon can be one of ADDON_LOADED or PLAYER_ENTERING_WORLD
the argument list varies by event but always follows the event parameter

When the PLAYER_ENTERING_WORLD event fires, the `isLogin` argument is actually the one named addonName in your function definition and the `isReload` argument is the one you have named isLogin and the one you have named isReload (the 3rd after the event parameter) will always be nil.

So this only works incidentally. Look at my code in this pull request, The event and ... argument list are always properly ordered. the argument list is assigned local variable names that make sense.

The localization files are still also only partially correct.
The english/default one is ok.
The other 3 are missing
```lua
local _, ShutUpRhonin = ...
local L = ShutUpRhonin.L
```
under the GetLocale() check and before trying to populate the localization array. L doesn't magically exist, at file scope without getting a reference to it from the ... vararg passed by the wow client.

**Comment by GovtGeek** [comment]
And this is why I asked for the second set of eyes. :)
I had noticed some odd behavior and I'm pretty sure it was the reload value being nil. I'll get to test that out later.
I looked at DBM's localization and they use a globally scoped table rather than one applied to the addon. That's how I missed that. I've also never taken the time to change locales to verify.

**Pull request closed without merging**
